### PR TITLE
Issue #12 Shocked Reactions

### PR DESCRIPTION
**Pull request by kaubri**
shocked-1
shocked-2
shocked-3

Adding 3 shocked reactions to the Surprised category.

### CODE REVIEW

**Comment by kaubri** [comment]
@uzair-ashraf I received this alert on Hacktoberfest.

> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

 Can "hacktoberfest-accepted" label be added to this PR?

**Comment by uzair-ashraf** [comment]
Hi @kaubri ! Sorry for the late response, been a long day.

I can add the label once its accepted, but unfortunately shocked-1 and shocked-5 are getting a little up there in terms of size, my ec2 instance is running out of space 😓 

If you can remove those I can approve it, thanks!!

**Comment by kaubri** [comment]
Can do! I’ll update today, thanks!

**Comment by uzair-ashraf** [comment]
Thank you!

**Review by uzair-ashraf — APPROVED** [review]

**Pull request merged**
