### PR TITLE
Added more reaction images

### PR DESCRIPTION
**Pull request by GriffinMLN**
Added more anime reaction images. Hope you like them :)

### CODE REVIEW

**Comment by uzair-ashraf** [comment]
Can you resubmit without these ones? The slackbot is used in my workspace 😓 
image

**Comment by uzair-ashraf** [comment]
This one needs to use kebab case, the api would have issues with spaces for the file names 
image

**Comment by uzair-ashraf** [comment]
After those you are approved! Thank you!

**Comment by uzair-ashraf** [comment]
Also, there is an existing smug3 now, will need to rename

**Comment by GriffinMLN** [comment]
@uzair-ashraf how's this? :)

**Review by uzair-ashraf — APPROVED** [review]

**Pull request merged**
